### ISSUE TITLE
to code creatively? my thoughts 

### ISSUE THREAD

**Issue by Airooadrith** [Montana-Media-Arts/120_CreativeCoding_Fall2017#10]
Is Creative Technology or Creative Coding an 'art form'?: 
In my opinion yes! I believe games and interactive media are certainly art-forms. I'm actually super interested in games that push the lines of aesthetics when it comes to the visual and the emotional. Okami, Borderlands, Minecraft, F.E.A.R, Element4l, LIMBO are all perfect examples of what I mean. each game is inherently different when it comes to the experience being crafted. Okami you feel like you're in a Japanese painting, borderlands a comic book. there not just the visual aesthetics either. there are also the emotional experiences being crafted. F.E.A.R might not be visually stunning, but it's atmosphere is whats selling it. just like when you look at a painting. not all are meant to look nice, some are meant to illicit certain emotions.  

What is a Media Artist? And, what is the difference, if any, between a media artist and creative technologist?:
as the name states, a media artist is an artist who uses visual media as his/her's art medium. the only difference I could think of, is that a media artist has a set design for the piece and has an intended medium to display it to it's ultimate effect. whereas a creative technologist is someone who uses certain technology to generate art to an unknown/semi-intended effect. less artistic control from the artist but a more individualized experience.

What is the relationship today between science and art?: 
I would say whatever you want it to be. I've seen masterful works of physics displayed in a very appealing way. and fantastic sound based pieces that show how vibrations interact with our world

**Comment by Madness666XD** [comment]
What is "creative technology" or "creative coding"?
creative technology or creative coding, are a language that is becoming involved in almost every aspect of modern life. Having a basic understanding of creative coding opens a world of new and creative possibilities, using the language of code and scripts to make professional art and dominate the world with imagination.
Is Creative Technology or Creative Coding an 'art form'?
YES
What is a Media Artist? And, what is the difference, if any, between a media artist and creative technologist?
Media arts takes programs such as krita, photoshop, and blender to make 3D, and 2D art in sketches on a computer using a drawing tablet or mouse.
Creative coding use some mathematics of slope and line work to digitally type in a design, as well as make websites and animation. 
How do you see Creative Technology fitting into the larger trends and flows of art?
Creative coding fits into larger trends by expanding how it is used. Trends like website creation, game development,and a low amount of digital art.   
What is the relationship today between science and art?
Today science equils art both are mankind's attempts to understand the universe. Art and science have different traditions and its audiences are very different. Scientists have trouble gaining insight, Artists have trouble with communication. Applied science is technology applied art is decoration so I see many differences but they are very similar it's just the way they are applied today that make them seem so opposite but in truth they have a lot in common. Science dives right into art with creative technology at its side.
What is the historical relationship between science and art?
Art is leaning into emotion, with color, music, or entertainment like dance or film, its wide spread like a circus performance or a ballay. Science is technical dealing with nature and society to find the reason for one's existence. Both dealt with nature in early times science with what you can and can not eat, art in making colored paints dyes and clothes. To a historical relationship I could not begin to guess but with one came the advancement of another.
