### ISSUE TITLE
Git issues and Questions

### ISSUE THREAD

**Issue by levigoddard** [Montana-Media-Arts/120_CreativeCoding_Fall2017#15]
I can not seem to change the name that appears on my git bash

User@DESKTOP-U0SNOJI MINGW64 ~
$ git config --system user.name "Levi Goddard"
error: could not lock config file C:\Program Files\Git\mingw64/etc/gitconfig: Permission denied

is the message I receive

 User@DESKTOP-U0SNOJI MINGW64 ~
$ git config --global user.name "Levi Goddard"

This is the message I receive when trying global

Am I missing something?

**Comment by michaelmusick** [comment]
If you make a couple commit’s (later in the tutorial), and then call `git status`, what do you see?

**Comment by madisonflaget** [comment]
you might also try opening the program (either terminal, command line, or Powershell) as an administrator. In Windows, you first go to the program icon as if you were going to open it. Then right click and select "Run as Administrator." If you are on Mac, a quick google search would show you how to do the same thing.

**Comment by dominikstallings** [comment]
I can't seem to use the "git" command in powershell. I installed it properly, what am I doing wrong?

**Comment by JonSwallow** [comment]
@levigoddard  I had the same issue. I was able to use it after a single commit in the Github desktop as @michaelmusick  described. Thanks for posting this, I would probably have been content to just use Github bash if I had not seen this, it made me want to solve the problem. 
![myshell](https://user-images.githubusercontent.com/31550331/30355152-b24f49c2-97ee-11e7-818e-44bb3154d3c5.jpg)

**Comment by lawlessofcourse** [comment]
I also had trouble entering the username and email on Powershell. I ended up just using the Git Bash application. Bash seems to be a lot easier to follow along with the videos using mac.

**Comment by levigoddard** [comment]
@madisonflaget 
Thank you. Opening it as an admin fixed it

**Comment by Cassidy7396** [comment]
so when you say to make our own repo to post homework to in git as a website, are you saying that we should just post it to answer git?

**Comment by michaelmusick** [comment]
I am asking you to create a git repository. This repository should also be hosted remotely on GitHub.com. You will do this using the GitHub Desktop Application to sync the local copy on your machine with the remote copy on GitHub’s servers. This is the place where you will host all of your homework for the semester. You will then link to these homework projects, proving a link to them on the course GitHub’s Wiki section. This way everyone can see each others work to build off of one another. 

Does that clear things up at all?
