### ISSUE TITLE
p5.js

### ISSUE THREAD

**Issue by kaitlinclifford** [Montana-Media-Arts/120_CreativeCoding_Fall2017#16]
I can't figure out how to start using p5.js I downloaded the zip folder but don't know where to go from there. I try to open different folders but it gives me error messages. I even unzipped it and I still don't know what I'm doing. Am I just being dumb or is there more to it than what I'm doing?

**Comment by JonSwallow** [comment]
Are we even there yet? I checked the website still week 2 for me on there.

**Comment by kaitlinclifford** [comment]
It says week 2 for me also, but I was just trying to open it and see if I could get it to work

**Comment by JonSwallow** [comment]
Ok cool, I was worried for a minute, thinking I missed something thanks for responding.

**Comment by Madness666XD** [comment]
if your having trouble with zip files download WinRAR it will easily open them in folders and locations for you.

**Comment by lawlessofcourse** [comment]
I also had trouble with the p5.js folder. I use WinRAR but I'm not sure where to go after extracting the files. I was planning on waiting till the course got to p5.js and see if that explains anything.
