### ISSUE TITLE
Git commit

### ISSUE THREAD

**Issue by StuffnThingz** [Montana-Media-Arts/120_CreativeCoding_Fall2017#18]
I'm on windows 10 using the command prompt and when I put in git commit -m 'initial commit for the repository and test1.txt' if just returns a bunch of errors.  Anyone else get this?

**Comment by JonSwallow** [comment]
@StuffnThingz  I did at first mine looks a little different because I had already set up outside the command line so I did a test set up here is a screenshot of it maybe it will help Tobin. I had to make sure the test.txt was present ect. My example is using Powershell.
![mygit](https://user-images.githubusercontent.com/31550331/30361460-63d1e388-9814-11e7-9d2a-2a69d45e0110.jpg)

**Comment by StuffnThingz** [comment]
Here's a screenshot of what I had.  I used the Git Bash app and everything went smooth.
![screenshot 4](https://user-images.githubusercontent.com/31543509/30361648-6c8eb05e-9815-11e7-8443-fc1a83edd517.png)

**Comment by JonSwallow** [comment]
@StuffnThingz  Right on someone else had a problem with git commands in Powershell. Maybe the same with Cmd. There is an issue on the board about it. Git Bash is the go to though. I was just ocd about getting Powershell to do what I wanted it to.

**Comment by MarcLenahan** [comment]
@StuffnThingz Try using Git Shell if you download the Git Hub desktop app and try following the steps again. I am using that and the commands have worked. Sometimes different command prompts and shells use different command terms. Hope this steers in the right direction.

**Comment by michaelmusick** [comment]
Great suggestion to use git bash. Sometimes command line programs on windows differ slightly and can be finicky. There is work going on by Microsoft to add a unix-like terminal to a future release of windows 10. So hopefully this will not be a problem I the near future. Until then, thank you everyone for the comments and help for your colleagues.

**Comment by StuffnThingz** [comment]
Thanks guys!  Git Bash is working for me.
