### ISSUE TITLE
Github Desktop

### ISSUE THREAD

**Issue by Tannerite00** [Montana-Media-Arts/120_CreativeCoding_Fall2017#19]
Github desktop keeps crashing on my computer. When I open task manager it says that its using between 50-90% of my computer's power. Is anyone else experiencing this?

**Comment by dominikstallings** [comment]
What kind of computer do you have? try to only use the necessary programs like Atom, Powershell (Unix) and one instance of google chrome.

**Comment by michaelmusick** [comment]
@Tannerite00 What OS do you have running? I have not had problems with this on my machines. I would second @dominikstallings suggestion of working with the absolute essential programs open and see if that changes your experience. Can you provide any other information that may help us troubleshoot with you?

**Comment by Tannerite00** [comment]
I've got a Lenovo Z70, and I'm running windows 10. I did have quite a few word and excel documents open, and its stopped crashing but its still incredibly slow.

**Comment by mmusick** [comment]
Would you have time to come by my office hours next week so we could look at it some more?

Also, if you think Atom is what is slowing you down, you may want to try another text editor, such as Adobe’s Brackets, or Sublime Text.

**Comment by Tannerite00** [comment]
Yes that would be great, and I will try some of the other text editors this weekend and let you know!

**Comment by katyspence** [comment]
For what it's worth, Atom is pretty slow on my computer, too, even though I have a good amount of processing power.
