### ISSUE TITLE
.md issues

### ISSUE THREAD

**Issue by levigoddard** [Montana-Media-Arts/120_CreativeCoding_Fall2017#20]
I cant seem to create a .md file, it keeps appearing as a .txt

**Comment by JonSwallow** [comment]
@levigoddard  if it wont work from the command line. Try this go to the file location, enable your view to file attributes. Right click rename .txt  backspace enter .md you will get a warning saying changing file type yada yada click ok. It should now be the file type you want and you can edit it in Atom.

**Comment by Glossyy** [comment]
If you're on Windows you can also go into notepad and when you save the file you choose the all files type in the drop down menu and save it as YOURFILENAME.md

**Comment by levigoddard** [comment]
@Glossyy
It dose not let me do so still

**Comment by Glossyy** [comment]
@levigoddard That is strange. Does your save window look like my save window? 

![image](https://user-images.githubusercontent.com/23406493/30408884-4af22086-98c7-11e7-92a1-e3b9f57915d3.png)

**Comment by michaelmusick** [comment]
@levigoddard <https://github.com/levigoddard> you should be able to also set the file type extension in Atom when you “Save As”, just has been mentioned with Note Pad.

**Comment by corypari** [comment]
Hey @levigoddard, your view is set to not show extensions which means you can't edit the .txt- instead it just saves as .txt by default when you create the file. To fix this, you can do two things. Follow these instructions, or look at the image below. I numbered the steps on the image so you can follow along!
1. go to where the file is in your documents or folders. At the top of the window, click the 'View' section. This should give you a bunch of new options. 
2. Click the 'details' section. I think from what I can tell you are using the icons or tiles option which doesn't let you change the file type.
3. Check 'File type extensions'. This lets you see what file types are, and change them if you want. It should show .txt now next to the file.
4. Right click your file, and click 'Rename'. Change the 'Example.txt' to 'Example.md'. Click off of the file and it will ask you "Are you sure you want to change this file type?" Click yes.

That should do it!

Let me know if that worked!!!!

**Comment by levigoddard** [comment]
@corypari
Your solution worked perfectly
