### ISSUE TITLE
“Open with Atom”

### ISSUE THREAD

**Issue by DMecam** [Montana-Media-Arts/120_CreativeCoding_Fall2017#23]
I have installed Aton and it seems to work properly. But when I open the GitHub App and I want to open the repository with Atom the only option that I find is “Open in an external editor”. When I select it, it’ll show me an error page “No suitable editors installed for GitHub Desktop to launch. Install Atom for your platform and restart GitHub to try again.”
I tried to reinstall Atom and it has full permissions. I’m on Windows 10.

**Comment by galen-koon** [comment]
I am on a Mac and had a similar problem, but was able to solve it with a reinstallation.  Here is a (outdated) forum about this, it might be of some use? https://discuss.atom.io/t/open-with-atom-option-in-github-desktop-application/20251/5
It seems like he/she was able to drag the repository into the atom icon and it would launch.  Maybe try that.  Sorry if this isn't helpful I honestly have no idea.

**Comment by corypari** [comment]
Is there an 'open with' option that expands out and includes the choice 'choose another app'? If so, try that, then click 'More Apps' again in the new window if it still isn't listed. 

Alternately you can try to force all files that end with either .md or .txt to open in Atom. To do this, right click your windows button, click search, then type in 'default app settings'. Scroll down and click 'choose by app file type'.  Scroll down to where .txt and .md are listed- click the default app to the left of it, then try to change that to Atom. This will make it so all of those documents will always open in Atom from now on.

**Comment by DMecam** [comment]
It seems to be working! Instead of dragging the repository into the atom icon I opened the folder directly in Atom. Also, I selected Atom as the default app to open .txt and .md. Thank you!!

**Comment by rachel-holton-burnett** [comment]
I'm having the same problem! Thank you for this thread- super helpful! Dragging the repo to Atom worked perfect. :)

**Comment by michaelmusick** [comment]
Nice job problem solving everyone. 

Sometimes technology just doesn't work and it takes some patient finagling. Also, if anyone is ever having problems you can't quiet solve, or want to look at again, please feel free to come by my office hours, with your computer if possible.

**Comment by Madness666XD** [comment]
Same problem at least your getting Atom to open though even that's becoming a struggle.
