### ISSUE TITLE
Issues with Access on Command Prompt

### ISSUE THREAD

**Issue by jackelynstob** [Montana-Media-Arts/120_CreativeCoding_Fall2017#24]
I have been working over 2 hours to try and gain access to my command prompt, I watched Youtube videos and read forums, and yet I still don't have access to create something as simple as a new file. 
This means I am still on step 1!! Has anyone else had any issues with this? I'm also on a windows laptop if that changes anything... 
I have tried running the command prompt as myself as a user and as the admin!! SOS

**Comment by DMecam** [comment]
Are you using PowerShell?

**Comment by jackelynstob** [comment]
I was just using the basic command prompt app that pops up when I type in the search bar

**Comment by jackelynstob** [comment]
![download](https://user-images.githubusercontent.com/31556621/30415979-a4ee838e-98e7-11e7-80eb-f44c64196e73.png)
It looks like this

**Comment by jackelynstob** [comment]
I just opened PowerShell and that seems to be working!! Thank you!

**Comment by DMecam** [comment]
You’re welcome! At first, I tried to use the basic command prompt app but I had problems too.

**Comment by lawlessofcourse** [comment]
If you have troubles following along with PowerShell another good program is GitBash. It works like Unix and is easier when following along with the lesson @jackelynstob
