### ISSUE TITLE
Shell Commands

### ISSUE THREAD

**Issue by RachelAgosto** [Montana-Media-Arts/120_CreativeCoding_Fall2017#25]
So for anyone that is having issues installing shell commands on windows go to the +install in Atom and type in shell commands there, it should pop up. This is also the same place where you can install the various packages Professor Musick suggested we install.

**Comment by michaelmusick** [comment]
Anyone? @RachelAgosto, what seems to be your problem? Is the atom shell command not working?

Have you tried typing `atom` in the command line.

**Comment by katyspence** [comment]
For the longest time, just typing atom or github in Powershell would not launch the programs. But tonight, it started launching the programs from Powershell (though suuuper slowly). Not sure why there was a delay, or if it had something to do with recent updates I just installed. Sorry I can't be more help.

**Comment by RachelAgosto** [comment]
I don't know what my issue is honestly, nothing was working for a while so I got some help from a pro coder from Nike to help me.
