### ISSUE TITLE
Observations

### ISSUE THREAD

**Issue by JonSwallow** [Montana-Media-Arts/120_CreativeCoding_Fall2017#26]
# Why Atom is as slow as Molasses in the Winter
## Auto encapsulating my tags
---
The number of packages installed on Atom cause a delay at startup
In settings under packages look at each package.
If you see a settings button for that particular package click it. It will tell you for ex.
This package added 101ms to startup time.
Some of these packages also interfere with each other.
---
I spent most of the day working through the material for MART 341, and wishing that Atom would perform like Notepad ++
I ended up killing a few of the packages by pushing disable. 
I wanted the encapsulation that I have with NP++.
I ended up finding a package called auto-complete html.
I changed the settings in the force section to "*"
[Find that Package Information Here](https://atom.io/packages/autoclose-html)
The result is now I do not have to bloody type nearly half as much and my production speed increases.
For those of you who have used NP++ you know what I am talking about. So I figured if anyone wanted 
that functionality there it is.

**Comment by tclark1178** [comment]
Yeah atom is slow for me too it really drags down performance.
