### ISSUE TITLE
Having trouble with Powershell. 

### ISSUE THREAD

**Issue by tclark1178** [Montana-Media-Arts/120_CreativeCoding_Fall2017#27]
Is anyone else having problems opening up documents with Powershell?

**Comment by JonSwallow** [comment]
@tclark1178  the cmdlet is invoke-item. Attaching a screenshot, I hope it helps ya out.
![screenshot 68](https://user-images.githubusercontent.com/31550331/30653175-a1b6b5ec-9de7-11e7-8d40-602f74c02028.png)

**Comment by tclark1178** [comment]
Thanks @JonSwallow Ill keep trying

**Comment by lawlessofcourse** [comment]
@tclark1178 I actually found that I prefer to use Git Bash as a command prompt. It is much easier to follow along in the lesson and has commands from Powershell and Unix. I had trouble opening and launching items in Powershell but once I used Git Bash I had no troubles.
