### ISSUE TITLE
open in browser

### ISSUE THREAD

**Issue by Tannerite00** [Montana-Media-Arts/120_CreativeCoding_Fall2017#29]
for some reason my open in browser packet does not want to work, did I download the wrong one? is there something else I need to be doing?

![help](https://user-images.githubusercontent.com/31601567/30837193-77ff727e-a220-11e7-9e3d-e033b61b972d.JPG)

**Comment by michaelmusick** [comment]
Make sure you are right-clicking on the `index.html` file and not the `sketch.js` file. 

We can only open html files in the browser, these then call JavaScript (sketch.js in our case) files. 

Any chance this is what was happening?

**Comment by Tannerite00** [comment]
Yes that was the issue thank you!

**Comment by mjohnson92** [comment]
Had this same issue, thanks!
