### ISSUE TITLE
Resolution

### ISSUE THREAD

**Issue by galen-koon** [Montana-Media-Arts/120_CreativeCoding_Fall2017#30]
I was able to create my "Hello World!" sketch, and everything seems to be in line with the example code on the website, but my resolution of the the actual text is definitely lacking.  It was actually doing the same thing in the pink example on the website, so I don't know if it's actually an issue or not. Is anyone else having this problem?
![screen shot 2017-09-26 at 2 56 34 pm](https://user-images.githubusercontent.com/31635768/30883908-f0217f36-a2ca-11e7-9953-d2c423e7cbe2.png)

**Comment by JonSwallow** [comment]
@galen-koon  [Mine did it too no worries](https://jonswallow.github.io/120-work/hw-3/)

**Comment by galen-koon** [comment]
@JonSwallow what do you mean no worries? Are you saying it's not something to be concerned about?

**Comment by JonSwallow** [comment]
@galen-koon  Yeah I am saying that is the inherent nature of the beast. You did the code right and that is all that counts. I would bet that resolution comes later. This is just the first steps into this deal. Everyone's will look the same.

**Comment by galen-koon** [comment]
@JonSwallow all right good to hear, thanks man! That makes me feel better.
