### ISSUE TITLE
Troubles with Atom.. kind of

### ISSUE THREAD

**Issue by lawlessofcourse** [Montana-Media-Arts/120_CreativeCoding_Fall2017#31]
I can't seem to get Atom to launch on my pc when I click on the desktop icon. It still does not run when I even right click and hit "Run as Administrator. The only way I can get it to open is by using my git bash command prompt. Then there I open the correct directory and type atom .directory and it opens it no problem. So basically Atom will only launch through command prompt, although this isn't a huge issue for me I would still like the program to launch when clicked on. Any Ideas?

**Comment by mmusick** [comment]
I have no ideas. This is quite strange. Have you had any luck googling?

**Comment by dominikstallings** [comment]
Is your main user set as the administrator of the OS? perhaps you don't have the right permissions set.

**Comment by MarcLenahan** [comment]
@lawlessofcourse If you look where the file location for atom is on your computer there is another application type file that should be able to be open up. If that file works I would right click and create a new shortcut on the desktop to see if that helps at all. I found my location folder in users on my main hard drive under the user you use then went to appdata then local and the atom file was list at the top. hope this helps point in the right direction.

**Comment by MeghanGp** [comment]
I had kind of a similar issue, I pinned it to my task bar while it was open to prevent the hassle and that worked vs. the desktop shortcut for whatever reason.

**Comment by lawlessofcourse** [comment]
Thanks everyone! Seems to be working right now!
