### ISSUE TITLE
"hw 3" not "hw-3"

### ISSUE THREAD

**Issue by TylerTheCreat0r** [Montana-Media-Arts/120_CreativeCoding_Fall2017#32]
When creating my new directory I used a space instead of the dash "hw 3" not "hw-3". So when creating the url it wont come up with my page. Is there any way to fix this? It wont allow me to rename the file in atom..

**Comment by JonSwallow** [comment]
@TylerTheCreat0r try just going to the location of the file in explorer and renaming it. Assuming you are on Windows. After you have renamed it you should see a change in Atom open recent projects if you have to. Then you can re-push through Github Desktop.

**Comment by TylerTheCreat0r** [comment]
Bless you. Closed atom, changed the name and opened again in atom, pushed through and the url works now. Thanks!
