### ISSUE TITLE
Error Pushing to Origin

### ISSUE THREAD

**Issue by trason-provence** [Montana-Media-Arts/120_CreativeCoding_Fall2017#34]
At the end of Homework Part 1, when being asked to push the changes I made, an error message is popping up. It is saying git credentials are not found. I have the repo open and ready, what am I missing?

**Comment by michaelmusick** [comment]
This most likely means you have somehow signed out.

Can you open preferences and make sure you are still signed into GitHub. You may need to try “Signing Out” Then “Signing in” again.

**Comment by trason-provence** [comment]
I tried singing in and out and the message is still popping up. I even
singed in and out of my Moodle and adjusted setting in the repository.

**Comment by michaelmusick** [comment]
First, what we are doing has absolutely no connection to Moodle. This is entirely separate from technologies provided by the University itself.

Second, bummer… Could you upload a screenshot?

**Comment by trason-provence** [comment]
![capture of error message](https://user-images.githubusercontent.com/31662446/30990231-bc1b257c-a45d-11e7-8887-fb8afd4ef49c.PNG)

**Comment by JonSwallow** [comment]
@trason-provence  I have not got a clue but I did find this on Github. You may find your solution there.
[Github error status 1](https://github.com/desktop/desktop/issues/2809) Apparently someone else had the same issue looks like a bugger to work around it though. Hope it helps. Probably @michaelmusick  may have to help you filter through this workaround for a solution.

**Comment by trason-provence** [comment]
Thank you @JonSwallow - I will check it out and see if I can make it work. If not, is there any chance you might be around your office @michaelmusick?

**Comment by mmusick** [comment]
Hey@ trason-provence, I am around until about 5:30 today. If you had some time to come by, we could definitely look at it. 

If you do come by, knock loudly, as I will be in my office recording videos.

**Comment by mmusick** [comment]
Also, @trason-provence. did you try the suggestion in the post?

Go up to the `Repository` menu and select `Open in Command Prompt`. It'll launch Command Prompt in the repository. Then run copy and paste `del /f .git\hooks\*` into Command Prompt and hit Return.

**Comment by trason-provence** [comment]
Be there soon.

**Comment by trason-provence** [comment]
Huge thank you to @JonSwallow! Those steps with @michaelmusick's help made it all pan out!

**Comment by JonSwallow** [comment]
@trason-provence  Glad I could help. Now I know it works I am fixin to go bookmark it in case that ever happens to me!! Cheers.
