### ISSUE TITLE
Anyway to recover lost file

### ISSUE THREAD

**Issue by StuffnThingz** [Montana-Media-Arts/120_CreativeCoding_Fall2017#36]
My computer shutdown in the middle of hw-4 (which I was almost done with).  I had been saving it frequently, but when I started the computer back up the file was empty and nothing was saved to the git desktop..  I should have backed it up better, but does anyone know a way to recover files like that???

**Comment by mmusick** [comment]
Sorry to hear Tobin, 

That is really stressful. I am at a lost how your computer could have lost the file, if it had been saved. What have you tried?

Also, does anyone have any ideas on this?

**Comment by StuffnThingz** [comment]
I tried doing the thing were you rename and folder and look for previous versions but I got nothing.  It's really bizarre, because I've closed it without saving and at least came back to were it was before I saved.

**Comment by katyspence** [comment]
Tobin, did you do a search for the file name? Maybe it was saving somewhere else inadvertantly.

A couple of times when I have copied/pasted these directories, it didn't grab the other content in them. (I was doing this through my command line, just to practice.) could something like that have happened?

**Comment by JonSwallow** [comment]
@StuffnThingz  Tobin I wish I knew an answer, but alas no such luck. I am glad you got it back somewhat I would try leaving Github Desktop open as you finish and push it often so you have an online backup.  I also use a batch file to frequently back up my documents to an external hard drive might be worth doing. 

Here is part of mine to give you an idea if you want to write a batch file. Of course you need an external hard drive to back up on. 

@ ECHO OFF
REM <Filename:JON.BAT>
REM <Programmer: Jon Swallow>
REM <4\10\2015>
REM <Purpose: to create a folder called ALLINFO with important system information and file lists>
ECHO HELLO WORLD 
ECHO COPYING CURRENT UNIVERSITY DOCUMENTS TO BACKUP
REM < XCOPY COMMAND ALL FOLDERS FILES AND VERIFY OVERWRITE>
XCOPY C:\Users\Owner\Documents /D/E/Y  I:\BKUP\STUP\PRSNLDOC\CURRENTDOCS /v
XCopy C:\users\owner\documents\"university of montana fall" /d/e/y  I:\bkup\stup\prsnldoc\currentdocs /v
ECHO DELETING TC FILES ON BACKUP
REM< DEL COMMAND FORCE>
DEL I:\BKUP\STUP\PRSNLDOC\EncryptedNow\TCFILE\*.* /P

REM <XCOPY COMMAND ALL FOLDERS FILES AND VERIFY OVERWRITE>
ECHO COPYING TC FILE
REM <XCOPY COMMAND>
XCOPY C:\Users\Owner\Documents\TCFILE /D/E/Y I:\BKUP\STUP\PRSNLDOC\EncryptedNow\TCFILE /v
ECHO COPYING PICTURES TO BACKUP
REM <XCOPY COMMAND>
XCOPY C:\Users\Owner\Pictures /D/E/Y I:\BKUP\PICS /v
REM <DIR AND THEN COPY COMMANDS>
ECHO DELETING RESIDUAL FILE
ECHO MAKING LIST OF PROGRAMS BACKUP
DIR F:\ /W/S > PROGRAMSBACK.TXT
ECHO COPYING TO ALLINFO
COPY PROGRAMSBACK.TXT C:\USERS\OWNER\DOCUMENTS\ALLINFO

**Comment by StuffnThingz** [comment]
Thanks @JonSwallow  I'll give that a shot

**Comment by JonSwallow** [comment]
@StuffnThingz  right on. [Microsoft reference on batch files](https://technet.microsoft.com/en-us/library/bb490869.aspx)     and [List of Command line commands](https://www.lifewire.com/list-of-command-prompt-commands-4092302)      of course tying **help** will bring up list. If you need help from there use the /? switch. Example xcopy /?      hope it works out Tobin.
