### ISSUE TITLE
Trouble viewing p5 code in browser

### ISSUE THREAD

**Issue by madisonflaget** [Montana-Media-Arts/120_CreativeCoding_Fall2017#37]
I was having trouble viewing the code that is displayed in-browser on the Creative Coding course website. At first I thought that I was just having trouble seeing the one pixel sized dot. Later on I realized that nothing was appearing at all. I found that this fixed itself after I clicked the [Live Example] link. That made all the code in the various boxes appear.

-Happy Coding

**Comment by Cassidy7396** [comment]
How did you get the live preview to work?

**Comment by madisonflaget** [comment]
Once I clicked on the [Live Example] link below the canvas, it started to display the results of the p5 code without issues. If does not work, I recommend refreshing the page and/or making sure that  you browser is up to date. DO NOT use Microsoft Edge or Internet Explorer as Microsoft is notorious for not keeping the code for their browsers up to date. Graphics and other things will often display wrong.
<img width="786" alt="capture" src="https://user-images.githubusercontent.com/21345991/31560750-bfc37100-b012-11e7-9077-deba5cf2d3a3.PNG">
