### ISSUE TITLE
I cant figure out how to make the strokes go away using nostroke

### ISSUE THREAD

**Issue by levigoddard** [Montana-Media-Arts/120_CreativeCoding_Fall2017#38]
When I put it in it makes the shape go away

    push();
    // Main Shirt Pieces go here
    nostroke();
    fill( 'rgb(0, 255, 0)')
    rect( -150, -150, 300, 300, 90, 90, 0, 0 );

    push();
    // Sleve Left
    nostroke();
    fill( 'rgb(0, 255, 0)')
    rotate(PI/4.0);
    rect( -175, 50, 75, 160, 90, 0, 0, 0 );

**Comment by JonSwallow** [comment]
@levigoddard  I had the exact same problem.
Here is what I did to work around it
```
// defining fill color outside of sandbox
fill('rgb(182, 167, 150)');
noStroke();

  // creating one of many sandboxes.
  push();

  // changing the centerpoint of x, y axis
  translate( -30, 0 );
  // adding a rotation for the hair
  rotate(radians(-7));
  rect( 178, 85, 240, 200, 45, 45, 120, 120 );
```

**Comment by rachel-holton-burnett** [comment]
Try capitalizing the S in Stroke. I'm pretty sure that's what fixed it for me. :)

**Comment by madisonflaget** [comment]
you have to capitalize the S in order for it to register. It also seemed to render better for me if I placed noStroke() after my fill.

**Comment by JonSwallow** [comment]
@levigoddard  I went back and tried to move mine inside the sandbox and it vanished just as you described. I looked further down and there is a spot where I defined it inside the sandbox that worked, but in that one spot no matter what I do it vanishes unless I defined it outside the sandbox. The difference I can see is the rotate that is the common denominator in both our cases. The time it worked inside the sandbox there was no rotate parameter.
```
 fill('rgb(182, 167, 150)');
 noStroke();

  // creating one of many sandboxes.
  push();
  // changing the centerpoint of x, y axis
  translate( -30, 0 );
  // adding a rotation for the hair
  rotate(radians(-7));
  rect( 178, 85, 240, 200, 45, 45, 120, 120 );
```
**Would not work inside sandbox**
```
        push();
        fill('rgb(182, 167, 150)');
        noStroke();

        // offsetting x y axis for placement of scaled item
        translate( 30, 30 );

        // scalling lower beard parameters for upper beard
        scale( 0.9);
        rect( 240, 330, 130, 98, 160, 160, 90, 90 );

        // closing sandbox
        pop();
```
**Would work in sandbox**

**Comment by ewilsey** [comment]
Add more push(); and pop(); Split your functions into subsections inside of your sandbox. Add one thing at a time and constantly refresh the html page. I ended up putting elements like ears and hair behind the head sandbox that contained the other features to get everything to line up properly on mine. Hoping yours is that simple of a fix. Cheers.

**Comment by RachelAgosto** [comment]
You need to capitalize the "S" in stroke. :)
