### ISSUE TITLE
Way to skew shapes?

### ISSUE THREAD

**Issue by MeghanGp** [Montana-Media-Arts/120_CreativeCoding_Fall2017#39]
Not exactly an issue, I'm just trying to find out if there is a way to skew things like the ellipse function? Basically, I want to skew an ellipse like the one below upward or downward, so it's not facing upright but rather at an angle such as / but I'm unsure if it is possible.

![ellipse](https://user-images.githubusercontent.com/31635585/31204391-e77caaae-a928-11e7-9590-45f41ffc76a1.PNG)

**Comment by michaelmusick** [comment]
Use `rotate()`

As discussed in the course content. https://montana-media-arts.github.io/creative-coding-1/modules/week-4/rotate/ <https://montana-media-arts.github.io/creative-coding-1/modules/week-4/rotate/>


so…

```js
// translate (0, 0) to another position
translate(56, 46);
// rotate clockwise, using degrees, converted to radians
rotate( radians(23) );
ellipse(0, 0, 20, 65);
```



Hope that helps!

**Comment by MeghanGp** [comment]
Definitely helps! I suppose I got ahead of myself on the assignment and hadn't looked that far in yet, thank you!
