### ISSUE TITLE
Media Artists today

### ISSUE THREAD

**Issue by cm107585** [Montana-Media-Arts/120_CreativeCoding_Fall2017#4]
1.) What is a Media Artist? What is the difference between a media artist and a creative technologist

      A.) A Media Artist like any artist, produces and works to create as a profession or a hobby while working within the realm of media as a medium. They create, paint, and solve with their own unique language and craft which they have taken the time to learn. We can help alter others’ perception  on day to day things as well as bridge the gap to allow understanding to those who are outside the medial realm. We paint the picture so they can understand and innately take away something from our work.

    B.) A Media Artist and a Creative technologist are fairly similar almost brothers. A Media Artist can work in digital art and animation/design, while Creative Technologists create new and artistic twists on technical things. Both work with the same bases and use the coding with their own developed language.

2.) What is the historical relationship between science and art?

     A.) Art and science have always gone hand in hand.You cannot have one without the other as many great artists in the past have proven. One Primary example of an artist who relied on science and art was Leonardo Da Vinci; Da Vinci was an artist of many forms; he was a renowned inventor, painter, architect, and a student of science. (Da Vinci) he used proportions to correctly draw the human figure as well as dimensional analysis (almost like coding) to build his structures and engineer things that were not only great discoveries but works of art that will remain in history forever.

History.com Staff. “Leonardo Da Vinci.” History.com, A&E Television Networks, 2009, www.history.com/topics/leonardo-da-vinci.

**Comment by Zachberry777** [comment]
@cm107585  #2 i like how you brought Leonardo into the history. He make fir the perfect example of the relations between science and art because of what he did. He created many things through the blue prints of his art.
