### ISSUE TITLE
Avoiding Confusion

### ISSUE THREAD

**Issue by JonSwallow** [Montana-Media-Arts/120_CreativeCoding_Fall2017#40]
In the Variable Scope section of the material, there is a variable called quarter_width, it is defined
 as = width * .05.
The fact is it is confusing because the variable should be named half_ width, or defined 
as  = width * 0.25.
Also there is no background color so that when the code runs depending upon your browser it looks like the dot falls at about a quarter of the width. 
I added a color background and placed dots at 25 percent 50 percent and 75 percent to clarify it for myself. 

 I know this is a long way around to explain a simple confusion, but it was enough to make me say "Let me deal with this later, "and walk a way for a bit. Because sometimes the simplest things can really throw you off kilter. I hope someone else catches this too; but if this helps then it is worth it.

![clipboard03](https://user-images.githubusercontent.com/31550331/31303759-02a3c44a-aad0-11e7-939d-7e9c7bfabeec.jpg)
![clipboard02](https://user-images.githubusercontent.com/31550331/31303760-0518d922-aad0-11e7-984d-0b02e9cf500f.jpg)

**Comment by madisonflaget** [comment]
Whoah! That is really weird. Thanks for the heads up!
