### ISSUE TITLE
Continual Loop

### ISSUE THREAD

**Issue by rachel-holton-burnett** [Montana-Media-Arts/120_CreativeCoding_Fall2017#41]
Hello! I am trying to get circles falling across the screen but once they are off the screen they don't come back up. They are also going really fast across the screen despite the fact that my frame rate is 1. I thought that everything would be on a continual loop if I didn't have mouseX and mouseY variables (which I don't for this part). Any insight and help in appreciated! Thank you!

**Comment by JonSwallow** [comment]
@rachel-holton-burnett  in order for them to come back it has to be a conditional loop, if, else etc. we haven't learned that yet here. So it is a  continual loop but not a conditional one. I don't know if that helps, I wanted to do the same thing you are talking about but I knew it was out for this one. I did end up timing some points differently to achieve a little variety.

**Comment by mmusick** [comment]
Yes to both. We have not yet learned how to actually keep things on the screen. 

If you canvas is 600, 400. And you try to draw a Y position at 500, it will be 100 pixels beyond the bottom of the canvas. We will talk about one way to address that this week, and another next.

**Comment by rachel-holton-burnett** [comment]
Thank you both!! I will keep playing with the distance.

**Comment by MikeStevens1161** [comment]
Thanks from me too It help me as well
