### ISSUE TITLE
Help With my Code

### ISSUE THREAD

**Issue by JakeTheFlare** [Montana-Media-Arts/120_CreativeCoding_Fall2017#42]
I need help with my code.  I am trying to make a yellow rotating sun, but it always comes out as a black oval and I can't seem to make it rotate.  Here's an example of my code down below.

_variables:_
var sunAngle = 0;
var sunRotationRate = 0;
var sunWidth = 300;
var sunHeight = 225;

_code:_
// creating the sun ellipse
  ellipse( 50, 80, sunWidth, sunHeight );
  noStroke();
  fill( 'yellow' );
  translate( 200, 200 );
  rotate( radians(sunAngle) );

// update the sun's angle position
  sunAngle = sunAngle + 45;

**Comment by JonSwallow** [comment]
@JakeTheFlare 
Here is the example from the material.
Rotate comes prior to the ellipse in @michaelmusick 's example try that, I hope it helps.

```
push();
    noStroke();
    fill( 'rgb(255, 176, 59)' );
    // move center
    translate( 0, -60 );
    // rotate head based on headAngle
    rotate( radians(headAngle) );
    // draw head skull
    ellipse( 0, 0, headWidth, headHeight );
```

**Comment by JakeTheFlare** [comment]
Helps a lot, thank you so much.  👍

**Comment by michaelmusick** [comment]
Also, we have to specify the fill color BEFORE trying to draw the ellipse.
