### ISSUE TITLE
Blinking shapes

### ISSUE THREAD

**Issue by galen-koon** [Montana-Media-Arts/120_CreativeCoding_Fall2017#45]
Hi, all. I'm trying to get a shape, in this case a red ellipse, to blink on a black rectangle. So every two seconds or so it comes on, and then disappears for the next four seconds before returning. I want to stagger three different shapes to do this so that only one is present at a time. Does anyone have any ideas on how to achieve this? So far from browsing google the only thing I can find would be to use the millis() command, but I was wondering if there was an easier way. 
Thanks!

**Comment by DMecam** [comment]
Hi, I searched about it and I also found that the milis() command is the best option. Perhaps, it would be easier to make a fade in and out effect instead of the blinking one. That way you would only need to create a color variable.
I’m sorry I couldn't find another solution.
