### ISSUE TITLE
Trying to make moon orbit planet

### ISSUE THREAD

**Issue by levigoddard** [Montana-Media-Arts/120_CreativeCoding_Fall2017#47]
I am trying to make my moon orbit the planet but it gets to close near Y 0
--------------------------------------
function setup() {
    // create a canvas to draw my portrait on
    createCanvas( windowWidth, windowHeight );
}

var moonRotationRate = 0;
var moonRate = 0;

function draw() {
    // set the background color
    background( 'rgb(6, 0, 0)' );
    // turn the cursor off
    noCursor();
    // UPDATE VALUES
    // base Moon rate on mouseY pos
    moonRotationRate = (mouseY * 0.1) - 20;
    // set the arm to spin at a constant rate
    moonRate = moonRate - 3;

    // *****************************
// Planet SANDBOX
// *****************************
push();

// make the person follow the mouse.
translate( mouseX, mouseY );
// Moon
push();
// Moon's info
strokeWeight( 10 );
stroke( 0 );
// draw the spinning Moon
push();
rotate( radians(moonRate) );
// define and draw the Moon
fill( 'rgb(51, 51, 51)' );
noStroke();
ellipse( moonRotationRate, mouseY, 30 );
pop();

push();
// Earth

strokeWeight( 10 );
stroke( 0 );
push();
// Draw earth
fill( 'rgb(0, 158, 167)' );
noStroke();
ellipse( 60, 0, 90 );
pop();
pop();
}

**Comment by quintinbruderer** [comment]
I am not fully sure of "how close is too close", so I fiddled with it a little and worked with this.

```function setup() {
  // create a canvas to draw my portrait on
  createCanvas(windowWidth, windowHeight);
}

var moonRotationRate = 0;
var moonRate = 0;
var earthSize = 90;

function draw() {
  // set the background color
  background('rgb(6, 0, 0)');
  // turn the cursor off
  noCursor();
  // UPDATE VALUES
  // base Moon rate on mouseY pos
  moonRotationRate = (mouseY * 0.1);
  // set the arm to spin at a constant rate
  moonRate = moonRate - 3;

  // *****************************
  // Planet SANDBOX
  // *****************************
  push();

  // make the planet and moon follow the mouse.
    translate(mouseX, mouseY);
  // Moon
    push();
  // Moon's info
      strokeWeight(10);
      stroke(0);
  // draw the spinning Moon
      push();
        rotate(radians(moonRate));
  // define and draw the Moon
        fill('rgb(51, 51, 51)');
        noStroke();
        //add a note here
        ellipse(moonRotationRate, ((mouseY/3) + earthSize), 30); //earthSize is called, no matter mouseY, the moon is only as close as earthSize. You could keep them from touching at all by also using moon's diameter. 
      pop();
      push();
  // Earth
        strokeWeight(10);
        stroke(0);
        push();
        // Draw earth
        fill('rgb(0, 158, 167)');
        noStroke();
        ellipse(earthSize/2, 0, earthSize); //I moved the moon's X so it's edge rested on mouseX. You can change this back. 
      pop();
    pop();
  pop();
}```

nasty long comments. I know. Is that something of what you're aiming for?

**Comment by levigoddard** [comment]
@quintinbruderer 

When I try to use your text i get a function setup error

**Comment by quintinbruderer** [comment]
Oh yeah! Crap. 
Don't copy the 3 ticks at the end of the snippet. 

Also, as simple as forgetting to copy the setup line.

```
function setup() {
  // create a canvas to draw my portrait on
  createCanvas(windowWidth, windowHeight);
}
```

just make sure to understand what is happening in the code and it seems right.
