### ISSUE TITLE
What should I do next? 

### ISSUE THREAD

**Issue by ewilsey** [Montana-Media-Arts/120_CreativeCoding_Fall2017#50]
I made an algorithmic painting but it doesn't seem like quite enough. Each time the page refreshes the background color changes, but I am wondering how I would incorporate moving shapes in one or more direction. Any suggestions? Here's what I have so far... https://ewilsey.github.io/120-work/hw-6/. I was thinking of making Scooby-Doo flower shapes that move across the page.

**Comment by JonSwallow** [comment]
@ewilsey  That is pretty cool, I would worry about meeting all the listed requirements as far as using the map() function, all the math listed as required etc. I thought mine was kinda lacking as well I ended up just going down the list and checking it off. I think some Scooby-Doo flowers would be the bomb though.

**Comment by ewilsey** [comment]
@JonSwallow Thanks for the quick reply and suggestion. I just added some maths and map functions, now the painting is more dynamic. No extra shapes yet.

**Comment by RachelAgosto** [comment]
@EricWilsey I think your algorithmic painting if fine the way it is. I feel
that if you added more it would become too cluttered. Sometimes simple is
best.
