### ISSUE TITLE
changing the fill color with the map function 

### ISSUE THREAD

**Issue by lbecker137** [Montana-Media-Arts/120_CreativeCoding_Fall2017#51]
```
r= map(mouseY, 0, windowHeight, 0,255);

fill(r,255,255,60);
ellipse(start, windowHeight/2, circle_size);

fill(r,255,255);
rect(windowWidth/3-100, windowHeight/2-32, side_length, side_length);
rect(windowWidth/3+40, (windowHeight/2)-4, sqrt(side_length), sqrt(side_length));
```

so I've got this code and the fill color changes for the squares when the mouse is moved, but not for the circles. Does making a shape translucent prevent you from changing the colors with the map function? or am I missing something?

**Comment by JonSwallow** [comment]
@lbecker137  I did not know so I did some research and found this thread on Github, I hope it helps. 
[Github thread concerning map function and opacity](https://github.com/processing/p5.js/issues/1826)

Although they are talking about hsb color it talks about opacity not working and they present a solution in the code which requires additional elements in the map function.
