### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by galen-koon** [Montana-Media-Arts/120_CreativeCoding_Fall2017#54]
I can't get my code to work, I have no idea why. All I want to do is create a circle that will move across the screen. Any help is greatly appreciated. 

function setup(){
  createCanvas( windowWidth, windowHeight);
}

function draw(){
  background('pink');

  for( var x = 0; x <= width; x++) {
    for( var y = 0; y < height; y++) {
    fill('black');
    ellipse( x, y, 40, 40);
  }
}
}

**Comment by michaelmusick** [comment]
> You are currently drawing an ellipse at every pixel in the canvas, every frame. 

Instead try, x+=80 and y+=90

**Comment by galen-koon** [comment]
Thank you!

**Comment by galen-koon** [comment]
Although @michaelmusick I don't understand why that is, I thought you had examples that went something like for (let x=0, x<width, x++)
