### ISSUE TITLE
I need some help with my code...

### ISSUE THREAD

**Issue by JakeTheFlare** [Montana-Media-Arts/120_CreativeCoding_Fall2017#55]
What is up my fellow GitHubbers?  I'm having some trouble with my code for this week's homework.  For my piece, I am trying to create eyeballs that will move all across the screen while creating more and more eyeballs.  Here’s what I have for my code…

// creating the variables and arrays

var words = [ "eye", "for", "an", "eye"];

var index = [ random ];

var pos = {
  x: 10,
  y: 50
};

// creating the setup function
function setup() {

  createCanvas( windowWidth,windowHeight );

}

// creating the drawing function
function draw() {

  background( 'black' );

  eyeBall( 40, 100, 1.0, 1.0 );
  eyeBall ( 200, 100, 1.0, 1.0 )

  myObj = map( mouseX, mouseY, 200, 300, 0 )

}

function text(){

  translate( 50, 55 );
  fill ( 155 );
  textSize ( 45 );
  text ( words[index], 12, 200 );

}

// creating the eyeBall function
function eyeBall( pos_x, pos_y, scale_x, scale_y ) {

  push(); // <- Start of Sandbox

  // 1. scaling and positioning the eyeBall

  translate( pos_x, pos_y );
  scale( scale_x, scale_y );

  // 2. drawing the eyeBall

  noStroke();
  fill( 'rgb(252, 253, 245)' );
  ellipse( 20, -35, 135, 135 );
  noStroke();
  fill( 'rgb(47, 79, 79)' );
  ellipse( 20, -35, 50, 50 );
  noStroke();
  fill( 'black' );
  ellipse( 20, -35, 25, 25 );
  noStroke();
  fill( 'white' );
  ellipse( 7, -45, 12, 12 );

  pop(); // <- End of Sandbox

}

This is a pretty difficult lesson, and I’m stuck, so any kind of help would be just great.

**Comment by JonSwallow** [comment]
@JakeTheFlare  I would look at @michaelmusick's example in week 10 and think of replacing the smiley with your eyeball. Something like that would probably work better with an empty array and a couple of for statements. I know that is not much help but maybe it will point you in the right direction. You are right it is a bugger of a week, I barely got mine written sorry I can't help more than that. I think he had some earlier examples of that smiley as a movable object. I took the easy way out and pushed it to mouseX and mouseY. One thing is for sure you are going to have to increment to make it move, remember the bouncy ball one from Shiffman? I was thinking something like that when you described what you want to do.

**Comment by JakeTheFlare** [comment]
Okay, thanks anyway.  The bouncy ball thing with Shiffman was from week 7 right?

**Comment by JonSwallow** [comment]
Yeah I think so, I bet someone is going to have a better suggestion I was just hoping to kind of point you in a direction that might spark something.  That one had a good example of incrementation. For sure I would look at the smiley code. See page 175 of Make Getting started with p5.js maybe that could help you could make the function of the eyeball and use random movement. Wish I could help more.
