### ISSUE TITLE
frame rates

### ISSUE THREAD

**Issue by kaitlinclifford** [Montana-Media-Arts/120_CreativeCoding_Fall2017#57]
I know this is last minute, but does anyone know if you can make different parts of your code have different frame rates?? Like if I wanted squares to be flashing slower than a circle in my code. I've tried doing it, and nothing seems to be working, so I don't know if there just isn't a way, or I'm not doing it correctly.

**Comment by lbecker137** [comment]
You could try having the squares flash every few frames rather than every frame with %? You can create a variable that counts the frames and set the square to flash every 3rd or 4th frame with an if statement.
