### ISSUE TITLE
for (let i...)

### ISSUE THREAD

**Issue by rachel-holton-burnett** [Montana-Media-Arts/120_CreativeCoding_Fall2017#58]
I am trying to use an array and the for loop and it keeps breaking my sketch. I can not figure out what I'm doing wrong and it's driving me insane! Any insight? Thank you!!

![image](https://user-images.githubusercontent.com/31631405/32997136-08abe1ba-cd49-11e7-9a97-b26c35640b51.png)

**Comment by JonSwallow** [comment]
@rachel-holton-burnett  I can not see anything wrong with what you have there. Double check your move method and see if something there is wrong. When I was doing this I had several times I broke my code there. Everything I can see there looks good. I wish I could help more.

**Comment by rachel-holton-burnett** [comment]
I was missing brackets on my draw function. Took me forever to figure it out! HOLY COW!!

**Comment by JonSwallow** [comment]
@rachel-holton-burnett  Now I see it yeah. Sorry I did not see it either. I am fired from proofreading code. Good thing its almost the end of the semester. Glad you found it.

**Comment by rachel-holton-burnett** [comment]
No please don't be sorry! I was just ripping my hair out trying to find it. It took me going line by line comparing it to the lecture to figure it out. :) I can now celebrate Thanksgiving break! :)
