### ISSUE TITLE
delta

### ISSUE THREAD

**Issue by StuffnThingz** [Montana-Media-Arts/120_CreativeCoding_Fall2017#59]
What exactly does delta do? I've used it before but I can't find exactly what it's for. Thanks!

**Comment by JonSwallow** [comment]
@StuffnThingz  delta is just a name @michaelmusick  has used in the past for movement, deltaX and deltaY for movement along the x or y axis.

**Comment by JakeTheFlare** [comment]
What @JonSwallow said.  But if you are using the code from the example, do not remove the word "delta" from the name, otherwise things will just get bizarre.  (Believe me, I tried it.)
