### ISSUE TITLE
Live Sketch is Blank

### ISSUE THREAD

**Issue by DomTSVG** [Montana-Media-Arts/120_CreativeCoding_Fall2017#61]
I'm having trouble with homework 11, I've written everything and checked everything myself plenty of times, but every time I save and try to view a live sketch, my window is absolutely blank. No errors or anything in the console.

I've attached my code. If someone could tell me what's causing my sketch to not show up, or what's wrong with my code, I'd appreciate it.

![image](https://user-images.githubusercontent.com/31668455/33258247-1a2e360e-d316-11e7-9340-4f84ad6d9750.png)
![image](https://user-images.githubusercontent.com/31668455/33258261-2bbe2744-d316-11e7-95a6-0681b8ad3e29.png)

**Comment by michaelmusick** [comment]
The first thing I notice is that you are not providing input parameters when you construct your boxes in the setup() function. 

Your constructor calls for ( x, y, size, color ). So when you create a box in line 21, you need to provide these values. (i.e. `new Box( width/2, height/2, 30, ‘blue’ )`

**Comment by DomTSVG** [comment]
Thank you so much for that. I really appreciate you pointing that out, and it fixed my problem!
