### ISSUE TITLE
Anyone know why the next week's assignment isn't up?

### ISSUE THREAD

**Issue by rachel-holton-burnett** [Montana-Media-Arts/120_CreativeCoding_Fall2017#62]
Am I missing something?...

**Comment by allenharguess701** [comment]
im not seeing it either.

**Comment by JonSwallow** [comment]
I bet it will be tomorrow. I believe he rotates the weeks depending on the weight of the other classes he knows what is assigned for example in 341 and I believe he works around those classes to give us time to do the other work since most of us have the same classes.
