### ISSUE TITLE
Ping Pong

### ISSUE THREAD

**Issue by Tannerite00** [Montana-Media-Arts/120_CreativeCoding_Fall2017#63]
I am coding a sort of game of pong, where the right side is just a wall and the player uses their mouse to steer the paddle on the left. I have made everything, but for the life of me cannot figure out how to get the ball and the paddle to recognize each other. below in my raw code I just have the rectangle as being a regular rectangle, not in a class by itself, because every time I try to use OOP with it, it crashes. any help would be greatly appreciated!

let balls = [];
const numOfBalls = 1;

function setup() {
    createCanvas(windowWidth, windowHeight);

    let init_x = 60;
    let init_y = 60;
    for ( let i = 0; i < numOfBalls; i++ ) {
        balls.push( new Ball( init_x, init_y ) );
        init_x += 100;
        if( init_x > width ) {
            init_x = 60;
            init_y += 100;
        }
    }
}

function draw() {
    background( 'Black' );
    fill('white')
    rect(1890, 0, 10, 1000)
    rect(0, 0, 10, 1000)
    rect(945, 0, 10, 30)
    rect(945, 60, 10, 30)
    rect(945, 120, 10, 30)
    rect(945, 180, 10, 30)
    rect(945, 240, 10, 30)
    rect(945, 300, 10, 30)
    rect(945, 360, 10, 30)
    rect(945, 420, 10, 30)
    rect(945, 480, 10, 30)
    rect(945, 540, 10, 30)
    rect(945, 600, 10, 30)
    rect(945, 660, 10, 30)
    rect(945, 720, 10, 30)
    rect(945, 780, 10, 30)
    rect(945, 840, 10, 30)
    rect(945, 900, 10, 30)
    rect(945, 960, 10, 30)

    for (let i = 0; i < balls.length; i++) {
        // call the ball's methods
        balls[i].move();
        balls[i].edgeCheck();
        balls[i].display();

        push();
        noCursor();
        translate(mouseX, mouseY);
        rect(10, 100, 20, 50);
        pop();
    }
}

class Ball {
    constructor(x, y, size) {
        this.color = 'white';
        this.size = 30;
        this.rad = this.size / 2;
        this.posX = x;
        this.posY = y;
        this.deltaX = random(-10, 10);
        this.deltaY = random(-10, 10);
    }

    display() {
        push();
        fill(this.color);
        // set the position of the ball
        translate(this.posX, this.posY);
        ellipse(0, 0, this.size);
        pop();
    }

    move() {
        this.posX += this.deltaX;
        this.posY += this.deltaY;
    }

    edgeCheck() {
        if (this.posX + this.rad >= width) {
            this.deltaX *= -1;

        }
        if (this.posY + this.rad >= height || this.posY - this.rad <= 0) {
            this.deltaY *= -1;

        }
    }
}

**Comment by JonSwallow** [comment]
@Tannerite00  Tanner, what Shiffman did was two balls since you only have the one you may have to compromise. 
```
// code I used in mine relating to two circles, spheres, bubbles basically ellipses this from the sketch.js 
  for (var j = 0; j < circles.length; j++) {
      if (i != j && circles[i].collision(circles[j])) {
       circles[i].colorShift();
       circles[j].colorShift();

// This is from the Class circles.js in my case 


  this.collision = function(alternate) {
    var d = dist(this.x, this.y, alternate.x, alternate.y);
    if (d < this.r + alternate.r) {
      return true;
    } else {
      return false;
    }
  }
```
So thinking along those lines instead of using the wall as your rebound point it may be worthwhile to create an object to bounce off of, for example you could create a thin rectangle the height of the screen along one wall and use that as your second object. The only problem I see is trying to get the ball to bounce off of it just like you would the actual edge of the screen. I am not sure if that helps spark anything but I do hope so. Cheers!!

**Comment by Tannerite00** [comment]
So I created a class for the paddle, and it follows the mouse. Everything is running smoothly except when I try to create a function for detecting a collision, it doesnt work. here is my updated code if anyone has any pointers!

let balls = [];
let paddles = [];
const numOfBalls = 1;
function setup() {
    createCanvas(windowWidth, windowHeight);

    //call paddle class, and call ball class, sets ball in spot. 
    paddles.push( new paddle);
    let init_x = 600;
    let init_y = 60;
    for ( let i = 0; i < numOfBalls; i++ ) {
        balls.push( new Ball ( init_x, init_y ) );
        init_x += 100;
        if( init_x > width ) {
            init_x = 600;
            init_y += 100;
        }
    }
}

function draw() {
    background( 'Black' );
    fill('white')

    //dotted middle line and surrounding lines for the "field"
    rect(1890, 0, 10, 1000)
    rect(0, 0, 10, 1000)
    rect(945, 0, 10, 30)
    rect(945, 60, 10, 30)
    rect(945, 120, 10, 30)
    rect(945, 180, 10, 30)
    rect(945, 240, 10, 30)
    rect(945, 300, 10, 30)
    rect(945, 360, 10, 30)
    rect(945, 420, 10, 30)
    rect(945, 480, 10, 30)
    rect(945, 540, 10, 30)
    rect(945, 600, 10, 30)
    rect(945, 660, 10, 30)
    rect(945, 720, 10, 30)
    rect(945, 780, 10, 30)
    rect(945, 840, 10, 30)
    rect(945, 900, 10, 30)
    rect(945, 960, 10, 30)

//calling the class characteristics for ball ad paddle
    for (let i = 0; i < balls.length; i++) {
        balls[i].move();
        balls[i].edgeCheck();
        balls[i].display();
        paddles[i].display();
        paddles[i].move();

    }

}
class paddle {
  constructor(x, y, size) {
    this.color = 'white'
    this.size_w = 20
    this.size_h = 50
    this.rad = this.size_w / 2
    this.posW = mouseX
    this.posZ = mouseY
  }
  display() {
    push();
    fill(this.color)
    translate(this.posW, this.posZ)
    rect(0, 0, this.size_w, this.size_h)
    pop();
  }
  move() {
    this.posW = mouseX
    this.posZ = mouseY
  }

}

class Ball {
    constructor(x, y, size) {
        this.color = 'white';
        this.size = 30;
        this.rad = this.size / 2;
        this.posX = x;
        this.posY = y;
        this.deltaX = random(-10, 10);
        this.deltaY = random(-10, 10);
    }

    display() {
        push();
        fill(this.color);
        // set the position of the ball
        translate(this.posX, this.posY);
        ellipse(0, 0, this.size);
        pop();
    }

    move() {
        this.posX += this.deltaX;
        this.posY += this.deltaY;
    }

    edgeCheck() {
        if (this.posX + this.rad >= width) {
            this.deltaX *= -1;

        }
        if (this.posY + this.rad >= height || this.posY - this.rad <= 0) {
            this.deltaY *= -1;

        }
    }


}
