### ISSUE TITLE
Ball Maze

### ISSUE THREAD

**Issue by mjohnson92** [Montana-Media-Arts/120_CreativeCoding_Fall2017#65]
Hello, I would like to make it so the ball will hit off any wall from my wall class but I am not sure where I would put the code because I have two classes.

I'm assuming it would go in the top section like in the draw or setup because if I use wall attributes and variables in the ball class it probably doesn't know what those are? 

I'm guessing it's similar to edgeCheck() by using an if statement but I am not sure where to begin really.

Here is my code so far, the ball and walls are working I just am not trying to get the ball to hit the walls.

let wall = [];
let ball;

function setup(){
    createCanvas( windowWidth, windowHeight);

    // create a new wall objects of class type "Wall"

    wall [0] = new Wall(50, 0, 10, 200 );
    wall [1] = new Wall( 100, 240, 10, 200);
    wall [2] = new Wall(150, 0, 10, 200 );
    wall [3] = new Wall( 200, 240, 10, 200);
    wall [4] = new Wall(250, 0, 10, 200 );
    wall [5] = new Wall( 300, 240, 10, 200);
    wall [6] = new Wall(350, 0, 10, 200 );
    wall [7] = new Wall( 400, 240, 10, 200);
    wall [8] = new Wall(450, 0, 10, 200 );
    wall [9] = new Wall( 500, 240, 10, 200);
    wall [10] = new Wall( 550, 0, 10, 200);
    ball = new Ball(width / 2, height / 2, 30);
}

function draw() {
    background(0);

    // call the wall's appearence

    wall[0].display();
    wall[1].display();
    wall[2].display();
    wall[3].display();
    wall[4].display();
    wall[5].display();
    wall[6].display();
    wall[7].display();
    wall[8].display();
    wall[9].display();
    wall[10].display();

    ball.appearence();
    ball.move();
    ball.edgeCheck();

}

///////////////////////////////////////////////////////////////
///////////////////// W A L L   C L A S S /////////////////////
///////////////////////////////////////////////////////////////

class Wall {
  constructor(x1, y1, width, height){
    this.x1 = x1
    this.y1 = y1
    this.width = width
    this.height = height
  }

  display() {
    push();
    // remove the walls outer stroke
    noStroke();
    // set the walls fill color
    fill(random(62, 255), random(0,255), 252 );
    // set the position of the wall
    translate( this.x1, this.y1 );
    rect( this.x1, this.y1, this.width, this.height );
    pop();

    }

}

///////////////////////////////////////////////////////////////
///////////////////// B A L L   C L A S S /////////////////////
///////////////////////////////////////////////////////////////

class Ball {
    constructor(x, y, size) {

        this.size = size;
        this.rad = this.size / 2;
        this.posX = x;
        this.posY = y;
        this.deltaX = random(-2, 2);
        this.deltaY = random(-2, 2);
    }

    appearence() {
        push();
        // remove the balls outer stroke
        noStroke();
        // set the balls fill color
        fill(random(62, 255), random(0,255), 252);
        // set the position of the ball
        translate(this.posX, this.posY);
        ellipse(0, 0, this.size);
        pop();
    }

    move() {
        this.posX += this.deltaX*2;
        this.posY += this.deltaY*2;
    }

    edgeCheck() {
        // check if the ball has hit a vertical wall (left or right walls)
        if (this.posX + this.rad >= width || this.posX - this.rad <= 0) {
            this.deltaX *= -1;
        }
        // check if the ball has hit a horizontal wall (top or bottom walls)
        if (this.posY + this.rad >= height || this.posY - this.rad <= 0) {
            this.deltaY *= -1;

        }
      }
    }

**Comment by allenharguess701** [comment]
I tried something similar at first but gave up. no matter what i did i could not get the variables to pass between the two classes.

**Comment by mjohnson92** [comment]
Thanks, thought about ditching this idea. Probably will now!
