### ISSUE TITLE
edgeCheck makes everything disappear

### ISSUE THREAD

**Issue by JakeTheFlare** [Montana-Media-Arts/120_CreativeCoding_Fall2017#66]
I need some help.  I've added an edgeCheck function to make my balloons bounce, but whenever I add it, it makes everything disappear on screen.  Here's my code below.

let balloons = [];
let num_of_balloons = 18;

// Creating the setup function.
function setup () {
    createCanvas ( windowWidth, windowHeight );
    frameRate ( 50 );

    for ( let i = 0; i < num_of_balloons; i++ ) {
        balloons.push ( new Balloons() );
    }
}

// Creating the drawing function to draw out the background and the balloons.
function draw () {
    background ( 'cyan' );

    for ( var i = 0; i < balloons.length; i++ ) {
        balloons[i].frame();
    }
}

//////////////////////////////////////////////////
//      BALLOON CLASS DEFINITION
//////////////////////////////////////////////////

// Creating a class called, Balloons.
class Balloons {

    // Creating the constructor that will give the balloons their actions and characteristics.
    constructor () {

        this.color = color( random(255), random(0), random(200) );

        this.size = ( 80, 140 );

        this.rad = this.size / 2;

        this.loc_x = random ( width );
        this.loc_y = random ( height );

        this.move_x = random ( -1, 0.5 );
        this.move_y = random ( -1, 0.5 );

    }

    // Creating the once per frame function.
    frame () {
        this.display ();
        this.move ();
        this.edgeCheck ();
    }

    // Display function: displays the content on the screen.
    display () {

        // Balloon Sandbox
        push ();

        translate ( this.loc_x, this.loc_y );
        noStroke ();
        fill ( this.color );
        triangle( -25, 85, 0, 60, 25, 85 );
        noStroke ();
        ellipse ( 0, 0, this.size );

        pop ();
        //End of Balloon Sandbox

    }

    // Move function: moves the balloons all around the screen.
    move () {
        this.loc_x += this.move_x;
        this.loc_y += this.move_y;
    }

    edgeCheck() {
         // check if the balloons have hit the left or right walls
        if (this.loc_x + this.rad >= width || this.loc_x - this.rad <= 0) {
            this.move_x *= -1;
          }
        }

**Comment by allenharguess701** [comment]
I feel yah. I had a heck of a time getting my objects to interact. Was going to do two different classes and just couldn't get the variables to pass.

**Comment by DMecam** [comment]
I think you are missing `}` at the end.
