### ISSUE TITLE
Collision Does Not Work

### ISSUE THREAD

**Issue by DomTSVG** [Montana-Media-Arts/120_CreativeCoding_Fall2017#68]
Hello again. I've been playing around and trying to get the new homework assignment updated so that the interactivity is proper, and I don't lose points or anything of the sort.

EDIT: There is a call for a bCheck in the draw function, that bCheck and call are gone for the time being, so please ignore that.

I've been trying everything I can think of to get collision to work in my code, but no matter what I try, either by following instructions and videos or by copying and modifying the code from the actual lesson, nothing works at all.

I need to know why, when it seems like the code snippet added to other's codes seems to work like a charm, while mine just does absolutely nothing when implemented. Any and all help would be massively appreciated.

Here's my current code:
![image](https://user-images.githubusercontent.com/31668455/33888673-02f9722c-df0b-11e7-8e05-b0b7d2728b2d.png)
![image](https://user-images.githubusercontent.com/31668455/33888711-19d47244-df0b-11e7-9ea2-b17e06d79270.png)
![image](https://user-images.githubusercontent.com/31668455/33888750-3060e39e-df0b-11e7-8b23-ba770f6a6d69.png)
![image](https://user-images.githubusercontent.com/31668455/33888774-41da6668-df0b-11e7-941e-725f9ddb5a90.png)

That's about it. I left out the collision code because, as I said, it ended up not working even when straight copied and modified. When I attempt detection I don't even get errors or anything, it's just that nothing happens at all. If you need the code I was attempting to use, here it is:
![image](https://user-images.githubusercontent.com/31668455/33888884-9f04200e-df0b-11e7-8ff4-42acea396fa3.png)

Any help with this would be wonderful, especially before later today, since it's my 21st birthday and I'm gonna drink a bunch at home and record some video games, so being able to take care of this first would be awesome. ;3

Thanks to whoever would be willing to help me!

**Comment by michaelmusick** [comment]
DOMINIC HAPPY BELATED BIRTHDAY!!!!!

Sorry you never got any help. Did you get anywhere on this? Could you send me (michael.musick@umontana.edu <mailto:michael.musick@umontana.edu>) your full code for this assignment, and I can take a look. Or post the code (not just images) here?
