### ISSUE TITLE
Open command in Powershell

### ISSUE THREAD

**Issue by StuffnThingz** [Montana-Media-Arts/120_CreativeCoding_Fall2017#7]
I'm trying to follow this tutorial on navigating directories, but Powershell (windows) doesn't recognize the "open ." command.  Anyone know what I'm doing wrong.  Thanks!

**Comment by mmusick** [comment]
Any luck on this Tobin?

**Comment by JonSwallow** [comment]
I noticed this was closed. Tobin I am not sure what you are looking for but, get-childitem may be the command you need. For example   C:\Users\Owner\Documents> get-childitem     will return the same results as dir. You can find a list of aliases by using the get-alias command. The set-location command is the same as cd. So for me I used the get-item to see where I was going and the set-location to get there. 
Hope that helped and I am not sure if I am breaking any rules here if I am my bad.

**Comment by ewilsey** [comment]
The Start command works to. Ex: Start Pictures

**Comment by mmusick** [comment]
Thank you all for your responses to this!

**Comment by StuffnThingz** [comment]
I used cmd instead of Powershell.  Seems to be a little more user friendly.

________________________________
