### ISSUE TITLE
Response to three questions  

### ISSUE THREAD

**Issue by tclark1178** [Montana-Media-Arts/120_CreativeCoding_Fall2017#8]
2. “Is Creative Technology or Creative Coding an 'art form'?” Yes as it can be expressive as with video games and the huge landscapes in them that digital designers work tirelessly on and also skillful as it does take practice to be a better coder.     

4. “How do you see Creative Technology fitting into the larger trends and flows of art”? The new Star Wars Movie "Rogue One" uses face redeveloping CGI to copy the likeness of the late actor Peter Cushing as a hallmark to the originals. We are starting to see this more prominent with the Marvel superhero movies also.    

5. “What is the relationship today between science and art?” As science is the search for truth It is objective therefore Art is subjective to one’s opinion on it. However, they both share a relationship of evolving discovery into the human condition.

**Comment by Zachberry777** [comment]
@tclark1178  #4 i totally agree with the relations of both evolving. They both are to create and to go through practice with error and succeeding.
